apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fluent-bit
  namespace: fleet-logging
spec:
  repo: https://github.com/fluent/fluent-bit-kubernetes-logging
  targets:
    - clusterSelector: {} # Isso irá selecionar todos os clusters
