#defaultNamespace: fleet-logging
#helm:
#  chart: fluent-bit
#  repo: https://fluent.github.io/helm-charts
#  version: "0.39.0"
#targetCustomizations:
#- name: gke-syseng-dev-01
#  clusterSelector:
#    matchLabels:
#      env: dev
#      service: infrastructure
#      location: gcp
#  helm:
#    valuesFiles:
#      - values/values.yaml
#      - values/gcp.yaml
#      - values/gke-syseng-dev-01.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fluent-bit
  namespace: fleet-logging
spec:
  repo: https://github.com/fluent/fluent-bit-kubernetes-logging
  targets:
    - clusterSelector: {} # Isso irá selecionar todos os clusters
