defaultNamespace: fleet-default
targetCustomizations:

- name: dev
  helm:
    values:
      serviceType: ClusterIP
      replicas: 1
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 2
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: ClusterIP
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
