defaultNamespace: fleet-logging
#namespace: fleet-local
helm:
  repo: https://fluent.github.io/helm-charts
  chart: fluent-bit
  version: "0.39.0"
targetCustomizations:

- name: dev
  helm:
    values:
      serviceType: ClusterIP
      replicas: 1
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 2
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: ClusterIP
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
